version: "3"

services:
  telegraf:
    image: telegraf:alpine
    environment:
      HOST_ETC: /hostfs/etc
      HOST_PROC: /hostfs/proc
      HOST_SYS: /hostfs/sys
      HOST_MOUNT_PREFIX: /hostfs
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/hostfs:ro
      - /etc:/hostfs/etc:ro
      - /proc:/hostfs/proc:ro
      - /sys:/hostfs/sys:ro
      - /var/run/utmp:/var/run/utmp:ro
    network_mode: host
    restart: always

  influxdb:
    image: influxdb:alpine
    ports:
      - 127.0.0.1:8086:8086
    volumes:
      # Data persistency
      # sudo mkdir -p /srv/influxdb/data
      - /srv/influxdb/data:/var/lib/influxdb
    restart: always

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      # Data persistency
      # sudo mkdir -p /srv/grafana/data; chown 472:472 /srv/grafana/data
      - /srv/grafana/data:/var/lib/grafana
    restart: always
